"""Render generated rows as SQL INSERTs or CSV.

The SQL emitter respects dependency order (parents first) so the script loads
cleanly into a database with foreign keys enforced.
"""

from __future__ import annotations

import csv
import io
from typing import Any

from .dialects.base import Dialect
from .model import DeferredUpdate, Schema


def to_sql(
    schema: Schema,
    data: dict[str, list[dict[str, Any]]],
    dialect: Dialect,
) -> str:
    lines: list[str] = [
        "-- generated by seedwright",
        "-- load order respects foreign-key dependencies; deferred cycles use UPDATEs",
        "",
    ]
    for tname, rows in data.items():
        if not rows:
            continue
        table = schema[tname]
        col_names = [c.name for c in table.columns]
        quoted_cols = ", ".join(dialect.quote_identifier(c) for c in col_names)
        lines.append(f"-- {tname}: {len(rows)} rows")
        for row in rows:
            values = ", ".join(
                dialect.quote_column_literal(row[col.name], col)
                for col in table.columns
            )
            lines.append(
                f"INSERT INTO {dialect.quote_identifier(tname)} "
                f"({quoted_cols}) VALUES ({values});"
            )
        lines.append("")
    for update in getattr(data, "deferred_updates", []):
        lines.extend(_render_update(schema, update, dialect))
    return "\n".join(lines)


def _render_update(
    schema: Schema,
    update: DeferredUpdate,
    dialect: Dialect,
) -> list[str]:
    table = schema[update.table]
    assignments = []
    for col_name, value in update.assignments:
        col = table.column(col_name)
        assignments.append(
            f"{dialect.quote_identifier(col_name)} = "
            f"{dialect.quote_column_literal(value, col)}"
        )
    predicates = []
    for col_name, value in zip(update.key_columns, update.key_values):
        col = table.column(col_name)
        predicates.append(
            f"{dialect.quote_identifier(col_name)} = "
            f"{dialect.quote_column_literal(value, col)}"
        )
    return [
        f"UPDATE {dialect.quote_identifier(update.table)} "
        f"SET {', '.join(assignments)} "
        f"WHERE {' AND '.join(predicates)};"
    ]


def to_csv(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()
