"""Render generated rows as SQL INSERTs or CSV.

The SQL emitter respects dependency order (parents first) so the script loads
cleanly into a database with foreign keys enforced.
"""

from __future__ import annotations

import csv
import io
from typing import Any

from .dialects.base import Dialect
from .model import Schema


def to_sql(
    schema: Schema,
    data: dict[str, list[dict[str, Any]]],
    dialect: Dialect,
) -> str:
    lines: list[str] = [
        "-- generated by seedwright",
        "-- load order respects foreign-key dependencies (parents first)",
        "",
    ]
    for tname, rows in data.items():
        if not rows:
            continue
        table = schema[tname]
        col_names = [c.name for c in table.columns]
        quoted_cols = ", ".join(dialect.quote_identifier(c) for c in col_names)
        lines.append(f"-- {tname}: {len(rows)} rows")
        for row in rows:
            values = ", ".join(
                dialect.quote_column_literal(row[col.name], col)
                for col in table.columns
            )
            lines.append(
                f"INSERT INTO {dialect.quote_identifier(tname)} "
                f"({quoted_cols}) VALUES ({values});"
            )
        lines.append("")
    return "\n".join(lines)


def to_csv(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)
    return buf.getvalue()
